- name: "install pyenv"
  homebrew: name=pyenv state=present

- name: "install pyenv virtualenv"
  homebrew: name=pyenv-virtualenv state=present

- name: "install rbenv"
  homebrew: name=rbenv state=present

- name: "install ruby build"
  homebrew: name=ruby-build state=present

- name: "install nodenv"
  homebrew: name=nodenv state=present

- name: "install go"
  homebrew: name=go state=present

- name: "install java"
  homebrew_cask: name=java state=present

- name: "install ksdiff"
  homebrew_cask: name=ksdiff state=present

- name: "install kaleidoscope"
  homebrew_cask: name=kaleidoscope state=present
  environment:
    HOMEBREW_CASK_OPTS: "--appdir={{ homebrew_cask_app_dir }}"

- name: "install sourcetree"
  homebrew_cask: name=sourcetree state=present
  environment:
    HOMEBREW_CASK_OPTS: "--appdir={{ homebrew_cask_app_dir }}"

- name: "install intellij idea"
  homebrew_cask: name=intellij-idea state=present
  environment:
    HOMEBREW_CASK_OPTS: "--appdir={{ homebrew_cask_app_dir }}"

- name: "install atom"
  homebrew_cask: name=atom state=present
  environment:
    HOMEBREW_CASK_OPTS: "--appdir={{ homebrew_cask_app_dir }}"

- name: "install alfred"
  homebrew_cask: name=alfred state=present
  environment:
    HOMEBREW_CASK_OPTS: "--appdir={{ homebrew_cask_app_dir }}"

- name: "install dash"
  homebrew_cask: name=dash state=present
  environment:
    HOMEBREW_CASK_OPTS: "--appdir={{ homebrew_cask_app_dir }}"

- name: "install evernote"
  homebrew_cask: name=evernote state=present
  environment:
    HOMEBREW_CASK_OPTS: "--appdir={{ homebrew_cask_app_dir }}"

- name: "install skitch"
  homebrew_cask: name=skitch state=present
  environment:
    HOMEBREW_CASK_OPTS: "--appdir={{ homebrew_cask_app_dir }}"

- name: "install dropbox"
  homebrew_cask: name=dropbox state=present
  environment:
    HOMEBREW_CASK_OPTS: "--appdir={{ homebrew_cask_app_dir }}"

- name: "install skype"
  homebrew_cask: name=skype state=present
  environment:
    HOMEBREW_CASK_OPTS: "--appdir={{ homebrew_cask_app_dir }}"

- name: "install spectacle"
  homebrew_cask: name=spectacle state=present
  environment:
    HOMEBREW_CASK_OPTS: "--appdir={{ homebrew_cask_app_dir }}"

- name: "install istat menus"
  homebrew_cask: name=istat-menus state=present
  environment:
    HOMEBREW_CASK_OPTS: "--appdir={{ homebrew_cask_app_dir }}"

- name: "install onepassword"
  homebrew_cask: name=onepassword state=present
  environment:
    HOMEBREW_CASK_OPTS: "--appdir={{ homebrew_cask_app_dir }}"

- name: "install punto switcher"
  homebrew_cask: name=punto-switcher state=present
  environment:
    HOMEBREW_CASK_OPTS: "--appdir={{ homebrew_cask_app_dir }}"

- name: "install whatsize"
  homebrew_cask: name=whatsize state=present
  environment:
    HOMEBREW_CASK_OPTS: "--appdir={{ homebrew_cask_app_dir }}"

- name: "install the unarchiver"
  homebrew_cask: name=the-unarchiver state=present
  environment:
    HOMEBREW_CASK_OPTS: "--appdir={{ homebrew_cask_app_dir }}"

- name: "install sketch"
  homebrew_cask: name=sketch state=present
  environment:
    HOMEBREW_CASK_OPTS: "--appdir={{ homebrew_cask_app_dir }}"

- name: "install cord"
  homebrew_cask: name=cord state=present
  environment:
    HOMEBREW_CASK_OPTS: "--appdir={{ homebrew_cask_app_dir }}"

- name: "install tunnelbear"
  homebrew_cask: name=tunnelbear state=present
  environment:
    HOMEBREW_CASK_OPTS: "--appdir={{ homebrew_cask_app_dir }}"

- name: "install tunnelblick"
  homebrew_cask: name=tunnelblick state=present
  environment:
    HOMEBREW_CASK_OPTS: "--appdir={{ homebrew_cask_app_dir }}"

- name: "install teamviewer"
  homebrew_cask: name=teamviewer state=present
  environment:
    HOMEBREW_CASK_OPTS: "--appdir={{ homebrew_cask_app_dir }}"

- name: "install reattach to user namespace"
  homebrew: name=reattach-to-user-namespace state=present

- name: "install tmux"
  homebrew: name=tmux state=present

- name: "install zsh"
  homebrew: name=zsh state=present

- name: "install fasd"
  homebrew: name=fasd state=present

- name: "install terminal notifier"
  homebrew: name=terminal-notifier state=present

- name: "install total terminal"
  homebrew_cask: name=totalterminal state=present

- name: "install virtualbox"
  homebrew_cask: name=virtualbox state=present

- name: "install vagrant"
  homebrew_cask: name=vagrant state=present

- name: "install packer"
  homebrew: name=packer state=present
