- hosts: developer
  roles: [developer]
  vars_prompt:
    - name: "dotfiles_projects_dir"
      prompt: "Where the projects should be cloned?"
      default: "{{ ansible_env.HOME }}/Projects"
      private: no
    - name: "dotfiles_scm_user_name"
      prompt: "Specify user name that should be used in SCM (git, hg) configs?"
      private: no
    - name: "dotfiles_scm_user_email"
      prompt: "Specify email that should be used in SCM (git, hg) configs?"
      private: no
    - name: "dotfiles_scm_github_username"
      prompt: "Specify GitHub username (optional)?"
      default: ""
      private: no
    - name: "dotfiles_aws_default_profile"
      prompt: "Specify Amazon Web Services default profile (optional)?"
      default: ""
      private: no
